env:
    browser: true
    es2021: true
    node: true
extends:
    - 'eslint:recommended'
    - 'plugin:jsx-a11y/recommended'
    - 'plugin:react/recommended'
    - 'plugin:react-hooks/recommended'
parserOptions:
    ecmaVersion: 12
    sourceType: module
    ecmaFeatures:
        jsx: true
plugins:
    - react
    - react-hooks
    - jsx-a11y
rules:
    array-bracket-spacing:
        - 2
        - never
    arrow-body-style: 2
    arrow-parens:
        - 2
        - as-needed
    arrow-spacing: 2
    block-spacing: 2
    brace-style:
        - 2
        - stroustrup
    camelcase: 2
    comma-spacing: 2
    comma-style:
        - 2
        - last
    computed-property-spacing:
        - 2
        - never
    consistent-return: 2
    constructor-super: 2
    curly: 2
    default-case: 2
    dot-location:
        - 2
        - property
    dot-notation: 2
    eol-last: 2
    eqeqeq:
        - 2
        - allow-null
    generator-star-spacing: 2
    indent:
        - 2
        - 4
    keyword-spacing: 2
    linebreak-style:
        - 2
        - unix
    new-cap:
        - 2
        - capIsNew: false
    new-parens: 2
    newline-per-chained-call: 2
    no-array-constructor: 2
    no-bitwise: 2
    no-const-assign: 2
    no-dupe-class-members: 2
    no-else-return: 2
    no-implicit-globals: 2
    no-inline-comments: 2
    no-lonely-if: 2
    no-multiple-empty-lines:
        - 2
        - max: 1
    no-multi-spaces: 2
    no-nested-ternary: 2
    no-new-object: 2
    no-process-env: 2
    no-return-assign: 2
    no-self-assign: 2
    no-self-compare: 2
    no-sequences: 2
    no-spaced-func: 2
    no-this-before-super: 2
    no-throw-literal: 2
    no-trailing-spaces: 2
    no-unmodified-loop-condition: 2
    no-unused-expressions: 2
    no-useless-call: 2
    no-useless-concat: 2
    no-unneeded-ternary: 2
    no-unused-vars: 2
    no-var: 2
    no-whitespace-before-property: 2
    object-curly-spacing:
        - 2
        - always
    object-shorthand: 2
    one-var-declaration-per-line: 2
    operator-linebreak:
        - 2
        - after
    padded-blocks:
        - 2
        - never
    prefer-arrow-callback: 2
    prefer-const: 2
    prefer-rest-params: 2
    prefer-template: 2
    quotes:
        - 2
        - single
    radix: 2
    semi:
        - 2
        - always
    space-before-blocks: 2
    space-before-function-paren:
        - 2
        - never
    space-in-parens:
        - 2
        - never
    space-infix-ops: 2
    space-unary-ops: 2
    template-curly-spacing: 2
    yoda: 2
